### ISSUE TITLE
How to use `SerperDevTool` with bing search?

### ISSUE THREAD

**Issue by nazkhan-8451** [crewAIInc/crewAI-examples#105]
I have `subscription_key` and `endpoint` for Bing search. Is it possible to integrate it with `SerperDevTool`. If yes, can you explain how?

**Comment by nanda-nainadurai** [comment]
On the [serper.dev ](https://serper.dev/) site, it says that they are the "The World's Fastest & Cheapest Google Search API". So, SerperDev does not natively support Bing.
