### ISSUE TITLE
Do we have any way to pass Dict or List as tool input?

### ISSUE THREAD

**Issue by Poojan66** [crewAIInc/crewAI-examples#111]
@tool("search elasticsearch")
def search_vector(input_data:Dict) -> str:
    """this is a tool to be used to fetch the similar vectors from elasticsearch 
    using embeddings and index_name database and return data recieved from elasticsearch
    :param input_data: dict, embeddings of a str and string, index name to search in elasticsearch.
    """

**Comment by apoorva1509** [comment]
Hey @Poojan66 , did you find any solution to your mentioned issue. I am facing the same thing as well.

**Comment by Poojan66** [comment]
Hi @apoorva1509 No I haven't found the solution sand didn't got any response from the team as well.
