### ISSUE TITLE
trip_planner is no longer working

### ISSUE THREAD

**Issue by Toasterme** [crewAIInc/crewAI-examples#120]
as the title said, the example is not working

pydantic_core._pydantic_core.ValidationError: 1 validation error for Task
expected_output
  Field required [type=missing, input_value={'description': "\nAnalyz...ick ideal destinations)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by shaihi** [comment]
Same error when running starter_template:
Traceback (most recent call last):
  File ".../starter_template/main.py", line 68, in <module>
    result = custom_crew.run()
             ^^^^^^^^^^^^^^^^^
  File ".../starter_template/main.py", line 39, in run
    custom_task_1 = tasks.task_1_name(
                    ^^^^^^^^^^^^^^^^^^
  File ".../starter_template/tasks.py", line 13, in task_1_name
    return Task(
           ^^^^^
  File ".../crewAIenv/lib/python3.12/site-packages/crewai/task.py", line 102, in __init__
    super().__init__(**config, **data)
  File ".../crewAIenv/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Task
expected_output
  Field required [type=missing, input_value={'description': "\nDo som...agent 1 backstory here)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by kaibrach** [comment]
You have to specify the `expected_output` for the task.
The `expected_output` field is mandatory for the task. See the description of the Task class and the mandatory `Field`:

```python
class Task(BaseModel):
    """ Class that represents a task to be executed.
   Each task must have a description, an expected output and an agent responsible for execution.
...

"""
```

For example:
```python
task = Task(
    description='Edit the blog post draft, improving its clarity, coherence, and engagement.', 
    agent=content_editor,
    expected_output='A refined finalized version of the blog post in markdown format'
)
```
