### ISSUE TITLE
How to get gpt 4 api key for free?

### ISSUE THREAD

**Issue by MirMax13** [crewAIInc/crewAI-examples#124]
Hi, i runned default code from CrewAI-LangGraph project and I got error:
 File "G:\Programs\anaconda3\Lib\site-packages\openai\_base_client.py", line 1030, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

After all, I realized that to run this project I need to have gpt-4 API key. So, may i get GPT4 API Key for free? Nowadays I am student and I learning AI, neural networks and I want to create my own project with default project from YouTube

**Comment by elAndyG** [comment]
You can check with your university. I'm reading some universities offering their students API keys.  If not, put $5 on an open ai account and use that. I put $10 on mine and i'm barely through it. Consider it educational expenses.
