### ISSUE TITLE
Browserless Free Tier No Longer Available: Alternative Required

### ISSUE THREAD

**Issue by DLWCMD** [crewAIInc/crewAI-examples#125]
I am trying to implement the _Trip Planner_ example function. However, it requires a _Browserless_ API key, and the free tier that you cited in your example is no longer available. Further, _Browserless_ may be required for other examples, so we need a free alternative. FYI, the minimum tier charge is now $200 as shown below.

What can you recommend?

Thanks.

<img width="428" alt="Screenshot 2024-06-24 at 11 19 41 AM" src="https://github.com/joaomdmoura/crewAI-examples/assets/48808570/7924e6a5-7d8e-42bb-a954-bad3cbf9d27e">

**Comment by faspina** [comment]
I was just looking at this. can't play $200 a month just to learn Crew AI. Any alternatives?

**Comment by Jzimmer01** [comment]
I am in same position.  I would like to learn by completing your tutorials and examples, but can't justify $200 month subscription.   An alternative would be greatly appreciated.

**Comment by faspina** [comment]
I found a Browerless docker container it looks like its the same API set to local host.  I might play with that over the next couple of days to see if I can get it to work. 

https://github.com/browserless/browserless?tab=readme-ov-file
