### ISSUE TITLE
Trying to use Surprise Trip Example: problem with poetry

### ISSUE THREAD

**Issue by cesaregerbino** [crewAIInc/crewAI-examples#135]
I'm trying to use the Surprise Trip Example on a Ubuntu 22.04 virtual machine.

My project structure is the following

![image](https://github.com/joaomdmoura/crewAI-examples/assets/4707083/96f16708-2093-46bd-a63a-fbb5e3331050)

 but trying this command ` poetry lock` this is the error

![image](https://github.com/joaomdmoura/crewAI-examples/assets/4707083/0859bad8-b1f9-40cf-a40e-0b31186bb437)

My poetry installed version is 1.1.12 and Python version is 3.10.12.

Any suggestion will be appreciated to solve.

NOTE: CrewAI works fine on the default project created after installation using OpenAI API KEY e Serper API KEY that I can try to use also in Surprise Trip example

**Comment by rafacalassara** [comment]
I got working using conda with this settings:
python = 3.11.9
poetry = 1.8.3
poetry-core = 1.9.0

I installed poetry using `conda install conda-forge::poetry`.
After executed `poetry lock && poetry install` and it's working.
