### ISSUE TITLE
Error during short_term search: Error code: 502

### ISSUE THREAD

**Issue by netsunn** [crewAIInc/crewAI-examples#188]
hello, I use ollama to provide embedding service, here's my code, but it show error info when i run crewai: rag_storage.py-rag_storage:186 - ERROR: Error during short_term search: Error code: 502
       
return Crew(
            agents=self.agents,  # Automatically created by the @agent decorator
            tasks=self.tasks,  # Automatically created by the @task decorator
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, 
            memory=True,
            embedder={
                "provider": "ollama",
                "config": {
                    "model": "mxbai-embed-large",
                    "base_url": "http://xxx",
                }
            }
        )

Maybe I configured the  ollama's base_url wrong?

**Comment by hsarvesh** [comment]
Hello, 

I was wondering for similar problem as well earlier. 

you needed to load LLM from crewai in crew.py along with agent config as below:

from crewai import Agent, Crew, Process, Task, **LLM**

@agent
def custom_name(self) -> Agent:
	return Agent(
		llm=LLM(model="ollama/llama3.2", base_url="http://localhost:11434"),
		config=self.agents_config['Custom_name'],
		verbose=True
	)

Please let me know if this helps.
