### ISSUE TITLE
what to do with pkl file after training? how to use it in generating improved results?

### ISSUE THREAD

**Issue by saurabhbidwai** [crewAIInc/crewAI-examples#190]
Hi, I have agents workflow and got the .pkl file so now how can we use that to generate new outputs? I can see .pkl file in some examples here but don't see its been used anywhere in the code?

**Comment by olaservo** [comment]
I had opened a related thread on the community support site which might help:
https://community.crewai.com/t/how-does-training-evaluation-actually-work-in-crewai/1341

Honestly I am a little confused about when/where to use github vs this site, but I did get a response there fairly quickly.
