### ISSUE TITLE
cannot import name 'TypeAliasType' from 'typing_extensions'

### ISSUE THREAD

**Issue by HuggingTech** [crewAIInc/crewAI-examples#21]
[/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_core_utils.py](https://localhost:8080/#) in <module>
     14 from pydantic_core import CoreSchema, core_schema
     15 from pydantic_core import validate_core_schema as _validate_core_schema
---> 16 from typing_extensions import TypeAliasType, TypeGuard, get_args, get_origin
     17 
     18 from . import _repr

ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

**Comment by Biancamazzi** [comment]
If you haven't solved it yet, could you please create an issue at https://github.com/joaomdmoura/crewAI/issues? Let's focus on addressing issues there.
