### ISSUE TITLE
How to connect the process to streamlit?

### ISSUE THREAD

**Issue by mbahmujono** [crewAIInc/crewAI-examples#43]
I wonder if I can put the process in the streamlit UI chat messages rather than in the terminal..

I think the approach would be tinkering with the logger. Or anyone else have suggestions?

**Comment by speaks999** [comment]
This would be very valuable. The example in the other thread shows the final output in Streamlit but not the log output as its being written to.  There must be a way to do this.

**Comment by julicq** [comment]
```import streamlit as st
# Initialize Streamlit app
st.title("CrewAI Task Execution")
# Display a message
st.write("Running CrewAI tasks...")
...
# Display result in Streamlit
st.write("##################################")
st.write(result)```
