### ISSUE TITLE
Can we have crewAI-examples on Hierarchical  Process

### ISSUE THREAD

**Issue by okoliechykwuka** [crewAIInc/crewAI-examples#58]
The documentation doesn't give much examples on that.

**Comment by slavakurilyak** [comment]
Have you seen [this](https://docs.crewai.com/how-to/Hierarchical/) and [this](https://docs.crewai.com/core-concepts/Processes/)?

**Comment by jkolyer** [comment]
Doc is fairly minimal and doesn't give transparency into how to setup the hierarchical crew.

**Comment by nkeilar** [comment]
One thing that's not clear to me is how to have some control of the manager agent... it seems to not have any idea sometimes which agent has access to which tools. It's not clear what the context of this agent is, which would be extremely useful in composing the other agents.
