### ISSUE TITLE
version incompatibility issue between several packages

### ISSUE THREAD

**Issue by GoldFlamingoAI** [crewAIInc/crewAI-examples#60]
Do you have any suggestions on how to resolve the error below?  I am just using OpenAI instead of Langchain but would love to use Langchain.

Because no versions of langchain-openai match >0.0.7,<0.0.8
 and langchain-openai (0.0.7) depends on langchain-core (>=0.1.26,<0.2.0), langchain-openai (>=0.0.7,<0.0.8) requires langchain-core (>=0.1.26,<0.2.0).
And because no versions of langchain-core match >0.1.26,<0.2
 and langchain-core (0.1.26) depends on langsmith (>=0.1.0,<0.2.0), langchain-openai (>=0.0.7,<0.0.8) requires langsmith (>=0.1.0,<0.2.0).
Because langchain (0.0.354) depends on langsmith (>=0.0.77,<0.1.0)
 and no versions of langchain match >0.0.354,<0.0.355, langchain (>=0.0.354,<0.0.355) requires langsmith (>=0.0.77,<0.1.0).
Thus, langchain-openai (>=0.0.7,<0.0.8) is incompatible with langchain (>=0.0.354,<0.0.355).
And because crewai (0.1.24) depends on langchain (>=0.0.354,<0.0.355), langchain-openai (>=0.0.7,<0.0.8) is incompatible with crewai (0.1.24).
So, because trip-planner-yt depends on both crewai (0.1.24) and langchain-openai (^0.0.7), version solving failed.

**Comment by akcserhant** [comment]
yea its bad, can't even validate tools now

**Comment by joaomdmoura** [comment]
sorry about that, with us focusing so much on the new versions of the main
lib these examples fell behind a little, I'll update them
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em sex., 23 de fev. de 2024 às 12:20, akcserhant ***@***.***>
escreveu:

**Comment by logikonline** [comment]
Please update these and pull in the requests.  It is very hard to use this.
