### ISSUE TITLE
Issue with imports

### ISSUE THREAD

**Issue by anmolgupta321** [crewAIInc/crewAI-examples#81]
crewai-beginner % python main.py          
Traceback (most recent call last):
  File "/Users/anmolgupta/Desktop/crewai-beginner/main.py", line 4, in <module>
    from agents import StockAnalysisAgents
  File "/Users/anmolgupta/Desktop/crewai-beginner/agents.py", line 3, in <module>
    from tools.browser_tools import BrowserTools
ModuleNotFoundError: No module named 'tools'

**Comment by mohsriach** [comment]
1. Ensure you have downloaded the package (for tools you can also use) -` pip install 'crewai[tools]'`
2. Make sure your file structure looks like the following - 
```
crewai-beginner/
|-- main.py
|-- agents.py
|-- tools
     |-- browser_tools.py
     
```
you need to have a '`tools`' folder that contains `.py` files from where you do the import.
