### ISSUE TITLE
Error import SerperDevTool or SeperDevTool

### ISSUE THREAD

**Issue by starry497** [crewAIInc/crewAI-examples#84]
https://github.com/joaomdmoura/crewAI-examples/blob/906e00d94008107393849c30fbf2c28c71141d65/job-posting/agents.py#L5

    from crewai_tools import WebsiteSearchTool, SeperDevTool, FileReadTool
ImportError: cannot import name 'SeperDevTool' from 'crewai_tools'

Found incorrectness while playing around with this tutorial. Got error importing both the modules: "SerperDevTool" & "SeperDevTool". 

Both the names are used in the tutorials/docs on the website of crewai. https://docs.crewai.com/core-concepts/Tools/#available-crewai-tools. Ctrl + F for both names and you will see the typo. 

Are there any bugs in this or some gotcha I need to be aware of ? 

Please help. TIA.

**Comment by yuripourre** [comment]
Did you install CrewAI tools?

```shell
pip install crewai-tools
```

**Comment by meVishnu** [comment]
Install crewai tools using  `pip install 'crewai[tools]'` and Change `SerperDevTool` to `SeperDevTool` in agents.py file

**Comment by mmartin-sub** [comment]
based on the [code](https://github.com/search?q=repo%3Ajoaomdmoura%2FcrewAI-tools%20SerperDevTool&type=code) from crew-tools, we should use SerperDevTool?
