### ISSUE TITLE
ACTION Input not working.

### ISSUE THREAD

**Issue by onedavidwilliams** [crewAIInc/crewAI-examples#97]
Action Input: {"query": "Tesla latest newsI apologize for the mistake. Here's my attempt at providing the best research analysis for Tesla:

Thought: To gather the necessary information for the report, I will start by scraping website content from Tesla's official website.

Action: Scrape website content

Action Input: {"website": "https://www.tesla.comI apologize for the mistake. Here is the corrected Thought and Action:

Thought: 
To gather the necessary information for the report, I will start by scraping website content from Tesla's official website.

Action: Scrape website content
Action Input: {"website": "https://www.tesla.com 

Action: Search the internet
Action Input: {"query": "Tesla latest news

Action Input: {"query": "Tesla latest newsI see what you're trying to do! You want me to help you with searching for recent news articles and press releases about Tesla.

Let's try again. Since we need to provide a string as input for the `Search the internet` action, let's correct that:

-------------------------------------------------------------------------------------------------------------
I am running llama3. It is the standard stock_analysis.

The issue seems that the trailing "} isn't added?

Any help is appreciated! Thank you.

**Comment by thedarklordkitten** [comment]
I have the same issue performing a simple PDF RAG search
